api/urls.py
from django.urls import path, include
from api import views
from rest_auth.views import LoginView,LogoutView
from rest_auth.registration.views import RegisterView

urlpatterns = [

    path('login', LoginView().as_view(),
         name="login"),
    path('logout', LogoutView().as_view(),
         name="logout"),
    path('register', RegisterView().as_view(),
         name="register"),
    path('furnitures/', views.FurnitureView.as_view(),
        name='furnitures'),
    path('furnitures/<int:id>/', views.FurnitureUpdateView.as_view(),
        name='furniture_update'),
    path('areas/', views.AreaView.as_view(),
        name='areas'),
    path('areas/<int:id>/', views.AreaUpdateView.as_view(),
        name='area_update'),
    path('rooms/', views.RoomView.as_view(),
        name='rooms'),
    path('rooms/<int:id>/', views.RoomUpdateView.as_view(),
        name='room_update'),
    path('buildings/', views.BuildingView.as_view(),
        name='buildings'),
    path('buildings/<int:id>/', views.BuildingUpdateView.as_view(),
        name='building_update'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf  import settings
from rest_auth.views import LoginView

from dashboard.views import index, register
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('register', register,
         name="register"),
    path('api/v1/', include('api.urls')),
    path('dashboard/', include(('dashboard.building.urls', 'dashboard.building'), namespace="building")),
    path('dashboard/', include(('dashboard.area.urls', 'dashboard.area'), namespace="area")),
    path('dashboard/', include(('dashboard.furniture.urls', 'dashboard.furniture'), namespace="furniture")),
    path('dashboard/', include(('dashboard.room.urls', 'dashboard.room'), namespace="room")),

]

templates/base.html
{% load static %}

<link href="{% static '/css/main.css' %}" rel="stylesheet" type="text/css" media="all"/>
<div id="content" class="content">
{% block content %}
{% endblock content %}
    <a href="{% url 'index' %}">
    <h4>Home</h4>
    </a>
</div>

templates/index.html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="../static/main.js" type="text/javascript"></script>


<a href="{% url 'building:index' %}">Building</a>
<a href="{% url 'room:index' %}">Rooms</a>
<a href="{% url 'area:index' %}">Areas</a>
<a href="{% url 'register' %}">Register</a>
<div>
    <button id="btnGetPersoneller">Get All Rooms</button>
    <div id="allPersonel" style="color:chocolate;font-size:12px;"></div>
</div>
<br>
<br>
<br>

<div>
  <form id="room-form" class="modal-content animate" method="post" action="">
    <div class="container">
      <label for="number"><b>Room Number</b></label>
      <input type="number" placeholder="Enter Room Number" id="number" name="number" required>
      </label>
    </div>
  </form>
</div>

templates/login.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)} 
  to {-webkit-transform: scale(1)}
}
  
@keyframes animatezoom {
  from {transform: scale(0)} 
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
</head>
<body>

<h2>Modal Login Form</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">
  
  <form id="modal" class="modal-content animate" method="post" action="">
      {%csrf_token%}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="img_avatar2.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" id="username" name="username" required>

      <label for="password"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" id="password" name="password" required>
        
      <button id="checkout" type="submit">Login</button>
      <label>
        <input type="checkbox" checked="checked" name="remember"> Remember me
      </label>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

<script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}


$(function(){
        $("#modal").on("submit", function(event) {
            event.preventDefault();

            var formData = {
                'username': $('input[name=username]').val(), //for get email 
                'password': $('input[name=password]').val() //for get email 
            };
            $.ajax({
                url: "{% url 'login' %}",
                redirect_url: "{% url 'index' %}",
                type: "post",
                data: formData,
                success: function(d) {
                    console.log(d['key'])
                    localStorage.setItem("Token", JSON.stringify(d));
                    console.log(d)
                    window.location.assign(this.redirect_url);
                }
            });
        });
    }) 
</script>

</body>
</html>